U/gcomoretto/defs
lsst-dm/dmtn-110 pull request #3
Opened 2019-05-24 22:29 UTC by gcomoretto

I would like to remove the definitions from this document and refer to the ones done in DMTN-106.

2019-05-24 22:58 UTC, timj requested changes
I'm okay with moving the definitions over to the other document. My main problem is that the commit history on this PR is not good. There are changes to infrastructure (gitignore, makefile, gitmodules) in the same commit as the content change. There is also a commit to add glossary and a commit to remove the glossary.  Please reset the branch and separate the changes to be so that build system changes are distinct from content.

2019-05-25 00:11 UTC, gcomoretto commented
The first commit now has all structural changes, including the local.bib file addition.
The second commit has content changes.
Is this OK, or should them be separated in 2 different branches?

2019-05-30 18:06 UTC, timj approved these changes

2019-05-30 18:06 UTC, timj commented on body.tex
> +The following (Eups) packages are proposed to be moved from science pipelines to the conda environment:
Eups -> EUPS

2019-05-30 23:02 UTC, merged